=== PLT2003/SewPages/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified"
	targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Nombre" />
				<xs:element ref="LongitudCircuito" />
				<xs:element ref="Anchura" />
				<xs:element ref="Fecha" />
				<xs:element ref="Hora" />
				<xs:element ref="Vueltas" />
				<xs:element ref="Localidad" />
				<xs:element ref="Pais" />
				<xs:element ref="Patrocinador" />
				<xs:element ref="Bibliografia" />
				<xs:element ref="Fotos" />
				<xs:element ref="Videos" />
				<xs:element ref="Origen" />
				<xs:element ref="Tramos" />
				<xs:element ref="Vencedor" />
				<xs:element ref="Clasificados" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Nombre" type="xs:string" />
	<xs:element name="LongitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="distanciaType">
		<xs:restriction base="xs:int">
			<xs:minExclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Fecha" type="xs:date" />
	<xs:element name="Hora" type="xs:time" />
	<xs:element name="Vueltas" type="xs:int" />
	<xs:element name="Localidad" type="xs:string" />
	<xs:element name="Pais" type="xs:string" />
	<xs:element name="Patrocinador" type="xs:string" />
	<xs:element name="Bibliografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="Enlace" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Enlace">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="href" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="Foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Foto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="Video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Longitud" />
				<xs:element ref="Latitud" />
				<xs:element ref="Altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="Tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Distancia" />
				<xs:element ref="Final" />
				<xs:element ref="Sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tramoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tramoType">
		<xs:restriction base="xs:float">
			<xs:minExclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Final">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Longitud" />
				<xs:element ref="Latitud" />
				<xs:element ref="Altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Sector" type="xs:int" />
	<xs:element name="Vencedor">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="duracion" type="xs:duration" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Clasificados">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="Clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Clasificado">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="posicion" type="posicionType" use="required" />
					<xs:attribute name="puntuacion" type="puntuacionType" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="posicionType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="3" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="puntuacionType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== PLT2003/SewPages/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<Circuito
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <Nombre>Chang International Circuit</Nombre>
    <LongitudCircuito unidades="metros">4554</LongitudCircuito>
    <Anchura unidades="metros">12</Anchura>
    <Fecha>2025-03-02</Fecha>
    <Hora>15:00:00</Hora>
    <Vueltas>26</Vueltas>
    <Localidad>Buriram</Localidad>
    <Pais>Tailandia</Pais>
    <Patrocinador>ThaiBev</Patrocinador>
    <Bibliografia>
        <Enlace href="https://www.bric.co.th">Página oficial Chang International Circuit</Enlace>
        <Enlace href="https://es.wikipedia.org/wiki/Chang_International_Circuit">Página wikipedia sobre Chang International Circuit</Enlace>
        <Enlace href="https://www.motogp.com/es/circuitos/chang-international-circuit">Página oficial de MotoGP</Enlace>
    </Bibliografia>
    <Fotos>
        <Foto alt="Foto del comienzo del circuito Chang International Circuit">../multimedia/changInternational1.webp</Foto>
        <Foto alt="Foto a vista de dron del circuito Chang International Circuit">../multimedia/changInternational2.jpg</Foto>
        <Foto alt="Mapa del circuito Chang International Circuit">../multimedia/changInternational3.webp</Foto>
    </Fotos>
    <Videos>
        <Video alt="Video de una vuelta al circuito Chang Internation Circuit">../multimedia/changCircuit.mp4</Video>
    </Videos>
    <Origen>
        <Longitud unidades="grados decimales">103.088056</Longitud>
        <Latitud unidades="grados decimales">14.957500</Latitud>
        <Altitud unidades="metros">180.6</Altitud>
    </Origen>
    <Tramos>
        <Tramo>
            <Distancia unidades="metros">255.59</Distancia>
            <Final>
                <Longitud unidades="grados decimales">103.0847156</Longitud>
                <Latitud unidades="grados decimales">14.9620019</Latitud>
                <Altitud unidades="metros">180.53</Altitud>
            </Final>
            <Sector>1</Sector>
        </Tramo>
        <Tramo>
            <Distancia unidades="metros">1024.85</Distancia>
            <Final>
                <Longitud unidades="grados decimales">103.0855894</Longitud>
                <Latitud unidades="grados decimales">14.9630569</Latitud>
                <Altitud unidades="metros">165.99</Altitud>
            </Final>
            <Sector>2</Sector>
        </Tramo>
        <Tramo>
            <Distancia unidades="metros">1273.19</Distancia>
            <Final>
                <Longitud unidades="grados decimales">103.086944</Longitud>
                <Latitud unidades="grados decimales">14.9575</Latitud>
                <Altitud unidades="metros">177.9</Altitud>
            </Final>
            <Sector>3</Sector>
        </Tramo>
        <Tramo>
            <Distancia unidades="metros">1273.19</Distancia>
            <Final>
                <Longitud unidades="grados decimales">103.088056</Longitud>
                <Latitud unidades="grados decimales">14.9575</Latitud>
                <Altitud unidades="metros">311.38</Altitud>
            </Final>
            <Sector>4</Sector>
        </Tramo>
    </Tramos>
    <Vencedor duracion="PT39M37.244S">Marc Márquez</Vencedor>
    <Clasificados>
        <Clasificado posicion="1" puntuacion="25">Marc Márquez</Clasificado>
        <Clasificado posicion="2" puntuacion="20">Alex Márquez</Clasificado>
        <Clasificado posicion="3" puntuacion="16">Francesco Bagnaia</Clasificado>
    </Clasificados>
</Circuito>
